### ISSUE TITLE
Packagist 配置有误

### ISSUE THREAD

**Issue by wi1dcard** [louislivi/smproxy#12]
![image](https://user-images.githubusercontent.com/25447002/48940466-a3d80480-ef52-11e8-9d52-10adbaa26228.png)

似乎自动 Update 没有配置。

**Comment by wi1dcard** [comment]
版本的 tag 我全部重新打了，从 v0.1.x 开始计，可以看下 <https://semver.org/lang/zh-CN/>

**Comment by louislivi** [comment]
@wi1dcard  好的，版本号现在最新的最好还是为1.2.0 为好 ，目前项目代码里面全局常量版本为1.2.0 不匹配 ， 而且项目以0.*版本开头不太友好 ，让人感觉项目不稳定 用1.0.*开头 ，而且最新的releases 与git版本中的代码不相同 bin 目录都缺少文件。

**Comment by wi1dcard** [comment]
@louislivi 😂问题是，的确还不稳定啊。那这样吧，我把前面的提交记录合并一下，直接打一个 `v1.2.0` 在原有的最新 release 上，你觉得如何？这样的话后面就从小版本开始迭代，例如 `v1.2.1` / `v.1.2.2`。

**Comment by wi1dcard** [comment]
周末两天我有事暂时不碰电脑，周一回来继续弄。

**Comment by louislivi** [comment]
好的，现在已经有些公司在生产环境使用了也已经解决绝大多数问题了，目前还是有点稳定的。

**Comment by wi1dcard** [comment]
@louislivi 另外我觉得，用全局常量做版本号不合适，和 git 无法同步，应该是从 git 内抽取版本号比较好些，我来处理吧。

**Comment by louislivi** [comment]
之前有人反馈过exec函数的问题，很多人禁用了exec函数

**Comment by louislivi** [comment]
可以使用https://wiki.swoole.com/wiki/page/263.html
要判断swoole版本再定义版本  这个是可以的，版本号目前在程序中只用来获取版本信息 其他地方暂未使用

**Comment by wi1dcard** [comment]
> 而且生产环境有些不会安装git在服务器中

生产环境应当使用 Release 版本的 PHAR，而不是 Git Clone Develop Branch。

> 可以使用https://wiki.swoole.com/wiki/page/263.html

我看 `ProcessHelper::run`内有使用 `proc_open` 执行，我觉得 `proc_open` 也可以，如何？

**Comment by louislivi** [comment]
可以的

**Comment by wi1dcard** [comment]
已解决。

<https://travis-ci.org/louislivi/smproxy/jobs/459001991>
