### ISSUE TITLE
有几点建议

### ISSUE THREAD

**Issue by amuluowin** [louislivi/smproxy#14]
1.client采用\Co\Client，根据消息swoole下个大版本计划移除异步API。
2.兼容docker，出个官方的docker镜像，可以采用docker的multi-stage build。基于容器的部署，可以直接sidecar进mysql容器。
3.连接数配置那里，生成dbconfig的时候，应该除以worker_num，这样配置的连接数才是实际数据库连接数。否则用户需要自己计算实际连接数，防止超出数据库配置。
4.worker_num配置建议支持function，例如一般连接数会设置为swoole_cpu_num()，或者swoole_cpu_num()*N这样。
5.增加一个配置，在服务启动的时候可以选择自动连接满maxSpareConns或者设定值或者不自动连接。默认自动满maxSpareConns。
6.日志组件可以兼容seaslog，SCG团队正在开发一整套日志收集，存储，分析系统，与seaslog完美结合。

**Comment by louislivi** [comment]
[v1.2.1-releases](https://github.com/louislivi/smproxy/releases/tag/v1.2.1) 已解决。
