### ISSUE TITLE
尽可能减少 Force Push

### ISSUE THREAD

**Issue by wi1dcard** [louislivi/smproxy#15]
修改提交记录 Force Push 之后我这边很容易把改过的提交记录又推上去，尽可能减少 Force Push 为好。

![image](https://user-images.githubusercontent.com/25447002/49005661-37ebdb00-f1a2-11e8-9db4-b22a69464bde.png)

**Comment by louislivi** [comment]
这个是我本地的github账号出现问题了，导致前面的提交全部显示其他邮箱 没有记录到github提交中。现在已经没问题了

**Comment by wi1dcard** [comment]
好的。
