### ISSUE TITLE
如果是有文件存在，并且是同名，需要先删除

### ISSUE THREAD

**Issue by wi1dcard** [louislivi/smproxy#16]
https://github.com/louislivi/smproxy/blob/e94eabd9576959caab4f48c79bdf5633d4a6edc1/src/Log/Log.php#L208

如上。

**Comment by louislivi** [comment]
不需要删除，这是判断日志目录是否存在 存在就返回True 开始写日志了，没有则创建目录。

**Comment by wi1dcard** [comment]
这个地方判断逻辑有问题，如果 `$log_path` 指向的路径是个文件，那么 `!file_exists($log_path)` 为假，然后继续判断 `!is_dir($log_path)` 为真，那么就会尝试创建此目录，然而这个路径下已经存在同名文件，所以需要先删除此文件，或者使用其他的逻辑处理。

**Comment by louislivi** [comment]
懂了，但是这种几率很小因为日志目录是按 logs/2018/11/24 这种格式的
```php
  if (!file_exists($log_path) || !is_dir($log_path)) {
            if (is_file($log_path)) {
                unlink($log_path);
            }
            return mkdir($log_path, 0644, true);
   }
```

**Comment by wi1dcard** [comment]
@louislivi 嗯嗯，尽可能避免为好，逻辑还是要严谨的。
