### ISSUE TITLE
下载解压使用?有composer安装使用吗?

### ISSUE THREAD

**Issue by gitzwt** [louislivi/smproxy#2]
大神可以打包composer安装使用吗?来个tp5的使用教程不

**Comment by wi1dcard** [comment]
这不是有吗：<https://github.com/louislivi/smproxy/blob/master/composer.json>

**Comment by louislivi** [comment]
直接下载运行服务即可 所有框架通用。这是服务不是扩展

**Comment by wi1dcard** [comment]
@louislivi 仔细看了下 `composer.json`，似乎很不完善，建议改一下名称描述类型等

**Comment by louislivi** [comment]
> @louislivi 仔细看了下 `composer.json`，似乎很不完善，建议改一下名称描述类型等

这个composer只是用来自动加载没有使用任何扩展 不用install之类的操作 下载即用

**Comment by louislivi** [comment]
后面有时间 会上传到composer类库中。

**Comment by wi1dcard** [comment]
@louislivi 嗯，只是建议，还是完善一些比较好。

**Comment by louislivi** [comment]
composer create-project --prefer-dist louislivi/smproxy smproxy
