### ISSUE TITLE
mysql8.0版本下问题咨询

### ISSUE THREAD

**Issue by gitzwt** [louislivi/SMProxy#22]
![image](https://user-images.githubusercontent.com/16423694/49266163-facc6500-f48f-11e8-8947-8c08914337ba.png)
将语句中的 'root'@'%' 替换成你所使用的用户, password 替换成其密码.
我的root用户是只允许127.0.0.1本地访问,我可以设置''root'@'127.0.0.1'吗? PHP项目里都是同一使用的root+127.0.0.1访问数据库,远程连接的有其他账号
如仍无法使用, 应在my.cnf中设置 default_authentication_plugin = mysql_native_password
这个怎么才能知道能不能使用?好像都是能启动服务的

**Comment by gitzwt** [comment]
proc_open这个函数是必须要打开的吗

**Comment by gitzwt** [comment]
我使用root@127.0.0.1 和其他新建的%账户都命令连接测试了  mysql -u自己账号 -p自己密码 -P3366 -h127.0.0.1
都是这样错误
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)

my.cnf中设置 default_authentication_plugin = mysql_native_password 也是设置了的

mysql版本是8.0.13,系统是centos7.4

**Comment by gitzwt** [comment]
服务启动不起来
ERROR:28000Access denied for user 'root'@'127.0.0.1' (using password: YES)

database.json 修改了自己的root账号密码后
WARNING: Server is shutdown!
ERROR:42000Unknown database 'dbname'
WARNING: Server is shutdown!

**Comment by louislivi** [comment]
ERROR:42000Unknown database 'dbname 将dbname 替换成数据库名称

**Comment by louislivi** [comment]
在database.json中

**Comment by gitzwt** [comment]
恩,最好这个database.json多数据库配置说明在readme里也介绍下

**Comment by wi1dcard** [comment]
> 恩,最好这个database.json多数据库配置说明在readme里也介绍下

@louislivi 我觉得配置项的文档应该重新改一下。

**Comment by louislivi** [comment]
嗯，后面会专门做一个网站。 就是现在没时间= =

**Comment by wi1dcard** [comment]
@louislivi 直接用 GitHub Pages 的模板 + Wiki 就能快速搞一个。

**Comment by louislivi** [comment]
@gitzwt 
@wi1dcard  英文需要麻烦下了...
[更新后的文档](https://github.com/louislivi/smproxy#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6)

**Comment by wi1dcard** [comment]
@louislivi 没问题，晚上回去搞定 😄
