### ISSUE TITLE
docker 下一直无法运行,求助

### ISSUE THREAD

**Issue by entimm** [louislivi/smproxy#23]
smproxy_1     | SMProxy version: v1.2.3
smproxy_1     |
smproxy_1     | Server starting ...
smproxy_1     | ERROR: The server have been running! (PID: 11)
smproxy_1     | ERROR: The server have been running! (PID: 11)
smproxy_1     | ERROR: The server have been running! (PID: 11)
smproxy_1     | ERROR: The server have been running! (PID: 11)
smproxy_1     | ERROR: The server have been running! (PID: 11)
smproxy_1     | ERROR: The server have been running! (PID: 11)
smproxy_1     | ERROR: The server have been running! (PID: 11)

**Comment by wi1dcard** [comment]
@louislivi 说到这个问题，我看了下 dockerfile 感觉又有个可能存在的问题，如果客户机器启动多个实例，由于 `logs` 目录暴露出来，那么 PID 就会引起冲突，这个 PID 文件应该是在镜像内，不应该暴露在宿主机的。

**Comment by entimm** [comment]
@louislivi 折腾了半天还是不行

具体配置看建的项目:https://github.com/entimm/docker-compose-smproxy

```
smproxy_1  | SMProxy version: v1.2.3
smproxy_1  |
smproxy_1  | Server starting ...
smproxy_1  | ERROR: The server have been running! (PID: 12)
smproxy_1  | ERROR: The server have been running! (PID: 12)
smproxy_1  | ERROR: The server have been running! (PID: 12)
smproxy_1  | ERROR: The server have been running! (PID: 12)
smproxy_1  | ERROR: The server have been running! (PID: 12)
smproxy_1  | ERROR: The server have been running! (PID: 12)
smproxy_1  | ERROR: The server have been running! (PID: 12)
smproxy_1  | ERROR: The server have been running! (PID: 12)
smproxy_1  | ERROR: The server have been running! (PID: 12)
smproxy_1  | ERROR: The server have been running! (PID: 12)
smproxy_1  | ERROR: The server have been running! (PID: 12)
docker-compose-smproxy_smproxy_1 exited with code 0
```

**Comment by louislivi** [comment]
@entimm 原因应该是你在本地启动过SMProxy 然后docker 指向了本地的logs目录出现了服务冲突，我刚测试docker 是可以正常使用的
```
docker run -itd -v youconfigpath/:/usr/local/smproxy/conf --name SMProxy imageId
```

**Comment by entimm** [comment]
始终还是没成功啊,崩溃了

**Comment by louislivi** [comment]
ERROR: The server have been running! (PID: 12) PID12是什么东西 这个得自己检查，这个错误是服务已启动在重复启动 因为PID12在进程中已存在 可以尝试删除server.pid文件 重启

**Comment by louislivi** [comment]
尝试先不挂载logs目录

**Comment by entimm** [comment]
没有重启 docker,就是 run 或者 up, server.pid 也删除过了, log 目录不挂载也还是一样的问题

**Comment by wi1dcard** [comment]
> @wi1dcard 可以在配置文件中配置pid路径

@louislivi OK。

**Comment by entimm** [comment]
原来SMProxy start了以后,命令就直接返回了,导致 docker 容器直接就退出了

**Comment by wi1dcard** [comment]
> 原来SMProxy start了以后,命令就直接返回了,导致 docker 容器直接就退出了

改成非 daemon 模式即可，应该不是退出，是不断重启 entry point。

**Comment by entimm** [comment]
改成非 daemon 模式搞定
