### ISSUE TITLE
此处似乎有问题

### ISSUE THREAD

**Issue by wi1dcard** [louislivi/smproxy#26]
<https://github.com/louislivi/smproxy/blob/67857d9d99c82f710e699dc967a34911ef2d529a/src/Parser/Util/ParseUtil.php#L172-L174>

感觉很怪异。

**Comment by louislivi** [comment]
很多方法是摘抄自java的 其实有些方法是预留的 现在还没用到

**Comment by wi1dcard** [comment]
嗯嗯，看 doc 看出来了，我修改了一些，更具备 php-style。
