### ISSUE TITLE
这个能不能 对执行过的SQL 做记录？

### ISSUE THREAD

**Issue by xutl** [louislivi/SMProxy#28]
这个能不能 对执行过的SQL 做记录？

**Comment by louislivi** [comment]
@xutl 如果是sql记录这个你可以自行查看mysql日志，如果是sql出现错误会进入smproxy/logs/*/*/*/mysql.log

**Comment by xutl** [comment]
其实我想的不是进入log文件，是 流计算，进入ETL

**Comment by aogg** [comment]
咋就不能提供下，看代码执行sql不是每个框架都有sql日志的  @louislivi
