### ISSUE TITLE
如果数据库和程序不在一个局域网部署

### ISSUE THREAD

**Issue by david7207** [louislivi/SMProxy#31]
按照这个逻辑的话，如果数据库和程序不在同一个局域网，也会有很好的表现吗？因为只需要程序启动的时候建立一个连接，程序再请求连接池返回的是已经存在的连接，那时间就可以忽略么？

**Comment by wi1dcard** [comment]
不可以，数据传输的时间是不会省去的。

**Comment by wi1dcard** [comment]
当然，也不建议将数据库暴露在外网（广域网）。

**Comment by david7207** [comment]
嗯，大概明白，谢谢
