### ISSUE TITLE
求助，遇到链接错误

### ISSUE THREAD

**Issue by david7207** [louislivi/SMProxy#32]
### Describe Your Environment (描述你的环境)

- System: 
- PHP version: php7.2
- Swoole version: 4.2.10-beta
- SMProxy version: latest

### How to Reproduce the Problem? (如何重现问题)

1. 启动程序，客户端连接不了，服务端报错

### 日志
[2018-12-17 23:08:40 *32060.4]	ERROR	sw_coro_check_bind (ERROR 10002): client has already been bound to another coroutine#43, reading or writing of the same socket in multiple coroutines at the same time is not allowed.
Stack trace:
#0  Swoole\Coroutine\Client->send() called at [phar:///home/src/smproxy/SMProxy/src/SMProxyServer.php:87]
#1  SMProxy\SMProxyServer->SMProxy\{closure}() called at [phar:///home/src/smproxy/SMProxy/src/Base.php:32]

**Comment by wi1dcard** [comment]
Hi，感谢你的反馈。简单看了一下，感觉可能是个隐含问题。

@louislivi https://github.com/swoole/swoole-wiki/blob/master/doc/4.14.4%20-%20%E9%94%99%E8%AF%AF%E4%BF%A1%E6%81%AF%EF%BC%9A%20XXXX%20client%20has%20already%20been%20bound%20to%20another%20coroutine.md

**Comment by david7207** [comment]
好难过，怎么之前没人发现呢，我直接配置运行就这个，对swoole不是很了解

**Comment by louislivi** [comment]
@david7207  不要用beta 版，用4.2.9 试试 ，目前没出现过这个问题，连接池是做了携程的调度的按理不会出现这个问题

**Comment by louislivi** [comment]
@david7207 3879dd8f76ee21a41f1261fccff7938e295c9bb4
