### ISSUE TITLE
php 安装版本声明错了

### ISSUE THREAD

**Issue by crazePhper** [louislivi/SMProxy#37]
php ./bin/SMProxy 
PHP Parse error:  syntax error, unexpected '?' in /home/test/SMProxy/vendor/humbug/box/src/FileSystem/file_system.php on line 497
test:~/SMProxy$ php -v
PHP 7.0.30 (cli) (built: Jun 27 2018 09:34:40) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.30, Copyright (c) 1999-2017, by Zend Technologies

**Comment by wi1dcard** [comment]
请问有什么问题？

从你不完全的描述猜测，请尝试删除 `vendor` 文件夹后，在你运行 SMProxy 的终端内使用 `composer install --no-dev`，并将输出内容贴出。
