### ISSUE TITLE
连接池连接泄露

### ISSUE THREAD

**Issue by breath-co2** [louislivi/SMProxy#39]
### Describe Your Environment (描述你的环境)

- System: mac os
- PHP version: 7.1
- Swoole version: 4.2.12 
- SMProxy version: v1.2.7@c3ea536

### How to Reproduce the Problem? (如何重现问题)

1. 配置 startConns：0，maxSpareConns：1，maxConns：3，swoole 的 worker_num：1，其它都默认，这样便于查看测试的问题
2. 启动服务器，开启1个mysql客户端（用mysql命令的客户端）这时看到mysql的show processlist 有1个SMProxy的连接，在客户端里use test; 并执行一个查询表现正常；
3. 不要关闭mysql客户端重启 SMProxy，然后在 mysql 里执一个上一次的 select，服务器出错，数据无法返回，尝试 use test 偶尔会提示成功，在mysql服务器的 show processlist后看到n多空闲连接，越来越多

### Expected Behavior (预期行为)
应该可以重连

### Actual Behavior (实际行为)
一直失败，而且导致服务器连接泄露，过一会可以重连，但是在mysql里的连接不自动断开，一直sleep状态

### More Information (更多信息)
无

**Comment by louislivi** [comment]
`SMProxy` 服务关闭未释放`MySQL` 连接，超过`MySQL`的`wait_timeout `会自动关闭。
