### ISSUE TITLE
swFactoryProcess_finish (ERROR 1004): send 122 byte failed, because connection[fd=31487] is closed.

### ISSUE THREAD

**Issue by 0711101021** [louislivi/SMProxy#41]
### Describe Your Environment (描述你的环境)

- System: 
- PHP version: 7.2.6
- Swoole version: 2.2.0
- SMProxy version: 1.2.7

### How to Reproduce the Problem? (如何重现问题)

1. 在smproxy/logs/swoole.log中出现了许多下面的错误
NOTICE	swFactoryProcess_finish (ERROR 1004): send 122 byte failed, because connection[fd=31487] is closed.

求告知这是怎么造成的，以及如何规避掉这个问题；
在业务访问上，我们也出现了有时候连不上的问题，本以为是是设置的连接数占满的问题，但是在mysql.log中没有出现连接数占满的告警。

...

**Comment by louislivi** [comment]
更新下swoole的版本吧
