### ISSUE TITLE
MariaDB10下问题咨询

### ISSUE THREAD

**Issue by dragon-D** [louislivi/SMProxy#42]
### Describe Your Environment (描述你的环境)

- System: 
- PHP version:  7.2
- Swoole version:  4.2.6
- SMProxy version: 1.2.7
- MariaDB 10

### How to Reproduce the Problem? (如何重现问题)

1. 正常查询，sql=show databases

### Expected Behavior (预期行为
 查询
...

### Actual Behavior (实际行为)
Packets out of order. Expected 1 received 2. Packet
mysqli::query(): MySQL server has gone away
...

### More Information (更多信息)
尝试用mysql5.7版本一切正常；
测试代码
`$conn = new mysqli('127.0.0.1','root','123456','test',3366);

if($conn->connect_errno){
    die('连接错误');
}

$sql = "show databases;";
$res = $conn->query($sql);
print_r($res->fetch_assoc());
$conn->close();`
...

**Comment by louislivi** [comment]
最新版本已解决
