### ISSUE TITLE
ERROR: SMProxy shutting down failed!

### ISSUE THREAD

**Issue by dvb3688** [louislivi/SMProxy#43]
### Describe Your Environment (描述你的环境)

- System:  Ubuntu18.04
- PHP version:  php7.1.8
- Swoole version:  4.3
- SMProxy version: 1.2.7

### How to Reproduce the Problem? (如何重现问题)
进入smproxy/bin目录执行开启服务
`./SMProxy start`
可正常访问代理后的服务及数据库。
但执行停止服务
`./SMProxy stop`
终端提示：**SMProxy is stopping ...**
等待须久，终端提示：**ERROR: SMProxy shutting down failed!**
查看swoole.log 并无报错信息，且提示：**NOTICE	Server is shutdown now.**。同时查看进程还在，但无法访问代理服务与数据库了。

**Comment by louislivi** [comment]
查看logs/日期目录下 system.log 日志信息

**Comment by dvb3688** [comment]
`[error] Uninitialized string offset: -6 (/home/wwwroot/smproxy/src/SMProxyServer.php:514)
[error] Uninitialized string offset: -6 (/home/wwwroot/smproxy/src/SMProxyServer.php:514)
[error] Uninitialized string offset: -6 (/home/wwwroot/smproxy/src/SMProxyServer.php:514)
[error] Uninitialized string offset: -6 (/home/wwwroot/smproxy/src/SMProxyServer.php:514)
[error] Uninitialized string offset: -6 (/home/wwwroot/smproxy/src/SMProxyServer.php:514)`

system.log 是在stop命令之前产生的日志， stop后没有生成日志。

**Comment by zhijielee** [comment]
解决了吗？我也出现了同样的问题
System: Ubuntu18.04
PHP version: php7.2
Swoole version: 4.3
SMProxy version: 1.2.7

**Comment by louislivi** [comment]
新版本已解决
