### ISSUE TITLE
使用mysql进行连接,选择数据库存在类似缓存的问题

### ISSUE THREAD

**Issue by xiaoyanger** [louislivi/SMProxy#44]
### Describe Your Environment (描述你的环境)

- System:  contos6.5
- PHP version:  5.3.29
- Swoole version:  4.0
- SMProxy version: 1.2.7

### How to Reproduce the Problem? (如何重现问题)

1.  直接按照配置连接
2. mysql_pconnect($host,$user,$passwd)连接数据库后直接使用 mysql_select_db 选择数据库 
3.  执行sql显示未选择数据库3D000No database selected 

### Expected Behavior (预期行为)

...直接显示查询结果

### Actual Behavior (实际行为)

...3D000No database selected  报错

### More Information (更多信息)

... 使用mysql_pconnect查询所有的数据库,然后循环显示数据库后,查询恢复正常

**Comment by louislivi** [comment]
需要在连接时指定数据库 ，不建议使用`mysql_select_db` 切换数据库
例如`new mysqli($servername, $username, $password, $dbname, $port);`
