### ISSUE TITLE
请问这个框架可以适用于多个数据库的情况吗

### ISSUE THREAD

**Issue by malphitee** [louislivi/SMProxy#45]
### Describe Your Environment (描述你的环境)

- System: CentOS6.5
- PHP version: 7.2
- Swoole version: 4.3.2
- SMProxy version: 1.2.7

### How to Reproduce the Problem? (如何重现问题)

1. 项目中使用到了多个数据库，需要根据用户登录信息切换数据库，在对应数据库中进行查询，而数据库信息已经写死在database.json中，想请问有没有办法动态的切换连接的数据库，即连接池中的对象连接的是不同的数据库，另外，数据库也可能动态的增减，除了更新json文件外还有什么方法能支持到这样的需求吗

### Expected Behavior (预期行为)

...

### Actual Behavior (实际行为)

...

### More Information (更多信息)

...

**Comment by louislivi** [comment]
必须提前进行数据库配置以及连接并且不推荐进行数据库切换
