### ISSUE TITLE
releases中没有1.8的版本

### ISSUE THREAD

**Issue by nsnake** [louislivi/SMProxy#46]
我在Centos7上使用
php7.2 
swoole4.3.2 发现cpu占用率在10%，查看文档说升级到1.8的版本，目前看到单PHAR只有1.7的版本

**Comment by jianghua** [comment]
https://github.com/louislivi/SMProxy/pull/47/commits/ac2d6362bf1281ebbf7c57b993fe345d4d488ae2
试试这个能不能修复你的问题

**Comment by nsnake** [comment]
我遇见的这个问题不是mysql回收时候造成的，而是运行后就基本保持在4颗CPU占用率都是10%上

**Comment by louislivi** [comment]
最新版本已解决
