### ISSUE TITLE
php版本问题

### ISSUE THREAD

**Issue by w1027918160** [louislivi/SMProxy#48]
### Describe Your Environment (描述你的环境)

- System: 
- PHP version: 
- Swoole version: 
- SMProxy version: 

### How to Reproduce the Problem? (如何重现问题)

1. 我系统上php有两个版本   一个 7.0，一个 5.4  ，，php-v 显示 是 5.4，，我启动 。./bin/SMProxy restart --console  报错，，应该是提示版本错误
2. 
3. 

### Expected Behavior (预期行为)

...

### Actual Behavior (实际行为)

...

### More Information (更多信息)

...

**Comment by w1027918160** [comment]
centos 系统的，，那个PHP 应该是自带的

**Comment by louislivi** [comment]
你可以指定php 位置运行 path/php SMProxy
