### ISSUE TITLE
配置多个数据库时，使用navicat链接会报database not selected

### ISSUE THREAD

**Issue by 262cheng** [louislivi/SMProxy#50]
### Describe Your Environment (描述你的环境)

- System: Ubuntu16.04
- PHP version: 7.3
- Swoole version: 4.3.5
- SMProxy version: 1.2.8

### How to Reproduce the Problem? (如何重现问题)
 配置多个数据库时，使用navicat12链接代码，执行命令会报database not selected

### Expected Behavior (预期行为)
能正确选择数据库执行相应命令
...

### Actual Behavior (实际行为)

...

### More Information (更多信息)

...

**Comment by louislivi** [comment]
![image](https://user-images.githubusercontent.com/23403807/60697414-bd93ee00-9f1c-11e9-9c7b-ce5183c56375.png)
未出现你说的问题，我之前测试到好像有一个版本navicat 确实有问题更新后解决了，不过推荐你navicat 还是连接原数据库信息，smproxy 主要是应用于业务开发。
