### ISSUE TITLE
Mac上无法启动worker

### ISSUE THREAD

**Issue by hongbaotong** [louislivi/SMProxy#51]
### Describe Your Environment (描述你的环境)

- System: macOS Mojave 10.14.5
- PHP version: 7.2.9
- Swoole version: 4.2.7
- SMProxy version: 1.2.8

### How to Reproduce the Problem? (如何重现问题)

1. 无法启动worker，调试发现是卡在SMProxyServer->setStartConns里的$client->recv();这一行 
![1562834346122](https://user-images.githubusercontent.com/3964571/61035818-6e592c00-a3fa-11e9-86d7-2d0fea7b0983.jpg)

**Comment by w1027918160** [comment]
好的，知道了




------------------ 原始邮件 ------------------
发件人: "Hong"<notifications@github.com>;
发送时间: 2019年7月11日(星期四) 下午4:40
收件人: "louislivi/SMProxy"<SMProxy@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [louislivi/SMProxy] Mac上无法启动worker (#51)




Describe Your Environment (描述你的环境)
  
System: macOS Mojave 10.14.5
 
PHP version: 7.2.9
 
Swoole version: 4.2.7
 
SMProxy version:
  
How to Reproduce the Problem? (如何重现问题)
  
无法启动worker，调试发现是卡在SMProxyServer->setStartConns里的$client->recv();这一行

**Comment by louislivi** [comment]
@hongbaotong  看看日志，贴出日志中的信息

**Comment by hongbaotong** [comment]
没有任何日志输出

**Comment by louislivi** [comment]
> 没有任何日志输出

贴出配置文件

**Comment by hongbaotong** [comment]
![1](https://user-images.githubusercontent.com/3964571/61109444-7aef8a00-a4b7-11e9-8e09-13b55cbd1e7a.png)
![2](https://user-images.githubusercontent.com/3964571/61109452-80e56b00-a4b7-11e9-9d09-40591788eee6.png)

**Comment by hongbaotong** [comment]
升级swoole扩展到4.4就可以了

**Comment by louislivi** [comment]
> 升级swoole扩展到4.4就可以了

我认为可能是端口问题 你使用9999以下的端口试试

**Comment by louislivi** [comment]
或者使用默认配置试试 将账号密码 数据库改对就行

**Comment by hongbaotong** [comment]
> 或者使用默认配置试试 将账号密码 数据库改对就行
这个就是我当时clone下来的默认配置，我只改了数据库登录信息，不过现在已经升级了swoole版本已经OK了

**Comment by louislivi** [comment]
> 或者使用默认配置试试 将账号密码 数据库改对就行
> 这个就是我当时clone下来的默认配置，我只改了数据库登录信息，不过现在已经升级了swoole版本已经OK了

默认端口是3366 而你的配置中是33066

**Comment by hongbaotong** [comment]
> 默认端口是3366 而你的配置中是33066

不是端口原因，我改回原来的swoole版本，端口改成3366也还是无法启动，升级到4.4就可以
