### ISSUE TITLE
自动退出

### ISSUE THREAD

**Issue by 571031767** [louislivi/SMProxy#52]
### Describe Your Environment (描述你的环境)

- System:  centos
- PHP version:  7.2
- Mysql version:  4.3
- Swoole version:  4.3
- SMProxy version:  1.25

### How to Reproduce the Problem? (如何重现问题)

1. 
[2019-07-16 14:41:32 *1195.1]	NOTICE	swFactoryProcess_finish (ERRNO 1004): send 73 byte failed, because connection[fd=37] is closed
WARNING: Server is shutdown!

### Expected Behavior (预期行为)

...

### Actual Behavior (实际行为)

...

### More Information (更多信息)

...

**Comment by louislivi** [comment]
@571031767  看一下其他几个日志文件中是否含有错误信息
