### ISSUE TITLE
预处理语句错误

### ISSUE THREAD

**Issue by Sebastianooooooo** [louislivi/SMProxy#54]
### Describe Your Environment (描述你的环境)

- System: 
- PHP version: 7.3
- Mysql version: 8.0
- Swoole version: 4.4.3
- SMProxy version: 1.2.9

### How to Reproduce the Problem? (如何重现问题)

1.TP5 框架使用smproxy链接数据库进行插入或者修改操作就会出现
SQLSTATE[HY000]: General error: 1149 HY000Unknown prepared statement handler (2) given to mysql_stmt_precheck  错误
2. 如果在执行这个sql语句的前面先进行一个select操作，则恢复正常。
3.这个情况只有当MySQL版本是8.0才会出现，5.7 是正常。
### Expected Behavior (预期行为)

...

### Actual Behavior (实际行为)

...

### More Information (更多信息)

...

**Comment by louislivi** [comment]
能发份能够复现的脚步吗，我这边测试未测出此情况。
```
<?php
        $start = microtime(true);
        var_dump($start);
        var_dump(Db::table('test')->insert(['id'=> 2,'name'=>'test','desc' => 'desc']));
        var_dump(Db::table('test')->where('id', 2) ->update(['desc'=> 'desc2']));
        print_r(microtime(true)-$start);exit;
```

**Comment by louislivi** [comment]
@Sebastianooooooo  这个问题我这边复现了，是因为php7.3+ 的缘故，我这边会根据解决这个问题。

**Comment by xiaoshenxianLy** [comment]
请问解决了吗

**Comment by louislivi** [comment]
@xiaoshenxianLy 你可以试试最新master分支上的代码，这个问题很奇怪，我这边后续没法复现，目前看来不是php版本的问题了

**Comment by louislivi** [comment]
c3baa1c5d6c5f297e4ed5d320faf118886fd6b01
