### ISSUE TITLE
如果我需要对sql进行处理后再执行 怎么办 对sql语句拦截处理 内置的有sql解析方便操作的吗

### ISSUE THREAD

**Issue by 54huige** [louislivi/SMProxy#55]
如果我需要对sql进行处理后再执行 怎么办 对sql语句拦截处理 内置的有sql解析方便操作的吗

我需要对每个sql新增一个where条件 但不是所有表都是如此 我要怎么办

**Comment by louislivi** [comment]
没有这个功能的
