### ISSUE TITLE
任何出错都把$e中errorInfo的错误码换成了1149

### ISSUE THREAD

**Issue by scguang301** [louislivi/SMProxy#57]
### Describe Your Environment (描述你的环境)

- System: centos7.2
- PHP version:  7.1.3
- Mysql version:  5.7
- Swoole version:  4.3.3
- SMProxy version:  1.2.8

### How to Reproduce the Problem? (如何重现问题)

try {
} catch(Throwable $e){
$e
}
1.  任何出错都把$e中errorInfo的错误码换成了1149。
看代码是MysqlProxy -》onClientReceive
  //ERROR Packet
                    if ($binaryPacket->data[4] == ErrorPacket::$FIELD_COUNT) {
                        $errorPacket = new ErrorPacket();
                        $errorPacket->read($binaryPacket);
                        $errorPacket->errno = ErrorCode::ER_SYNTAX_ERROR;
                        $data = getString($errorPacket->write());
                    }
请问和这样处理，而不是直接转发mysql的错误？

### Expected Behavior (预期行为)
mysql的错误码
...

### Actual Behavior (实际行为)

...

### More Information (更多信息)

...

**Comment by louislivi** [comment]
3f6eb03c84247fbae5bc200a5cdf460476d5a3b2
