### ISSUE TITLE
原生与SMProxy 使用mysqli对比性能

### ISSUE THREAD

**Issue by lxge** [louislivi/SMProxy#58]
### Describe Your Environment (描述你的环境)

- System: centos7
- PHP version: 7.2
- Mysql version: 5.5
- Swoole version: 4.4
- SMProxy version: 1.2.9

### How to Reproduce the Problem? (如何重现问题)

**1. 原生mysqli访问**
```
<?php

    //使用面向对象进行数据库的连接，在创建对象的时候就自动的连接数据

    $mySQLi = new MySQLi('localhost','root','123456','app',3306);

    

    //判断数据库是否连接

    if($mySQLi -> connect_errno){

        die('连接错误' . $mySQLi -> connect_error);

    }
     
    //选择数据库
    /* change db to world db */
    //$mySQLi->select_db("app");

    //设置字符集

    $mySQLi -> set_charset('utf8');

    //编写sql语句并执行

    $sql = "select * from admin";

 

    //发送sql语句并执行，如果是select语句，返回的是一个对象，其他的返回来一个boolean.

    $res = $mySQLi -> query($sql);


    //使用$res对象里面的fetch_assoc()取出里面的数据.

    while($row = $res->fetch_assoc()){

     var_dump($row);

    }

    $res -> free();

    $mySQLi -> close();
```

2. SMProxy访问
```
<?php

    //使用面向对象进行数据库的连接，在创建对象的时候就自动的连接数据

    $mySQLi = new MySQLi('127.0.0.1','root','123456','app', 3366);


    //判断数据库是否连接

    if($mySQLi -> connect_errno){

        die('连接错误' . $mySQLi -> connect_error);

    }
     
    //选择数据库
    /* change db to world db */
    //$mySQLi->select_db("app");

    //设置字符集

    $mySQLi -> set_charset('utf8');

    //编写sql语句并执行

    $sql = "select * from admin";

 

    //发送sql语句并执行，如果是select语句，返回的是一个对象，其他的返回来一个boolean.

    $res = $mySQLi -> query($sql);


    //使用$res对象里面的fetch_assoc()取出里面的数据.

    while($row = $res->fetch_assoc()){

     var_dump($row);

    }

    $res -> free();

    $mySQLi -> close();
```

3. 
原生访问数据库
ab -c 100 -n 1000 http://192.168.1.169:81/test/ab/mysqli_5.6.php  
耗时:5s
使用连接池
ab -c 100 -n 1000 http://192.168.1.169:81/test/ab/mysqli_pool_5.6.php
耗时:6s
### Expected Behavior (预期行为)
不是应该用连接池更快的吗,配置大都是系统默认的maxConns是cpu*20
查看运行状态
/me/smproxy/SMProxy status
SMProxy[v1.2.9] - Linux localhost.localdomain 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64
Host: 0.0.0.0, Port: 3366, PHPVerison: 7.2.6
SwooleVersion: 4.4.5, WorkerNum: 10
Process :  40 total,  4 query,  36 sleep

作者有空能不能看一下啊 这个就是想试一下能够提升多少性能的

**Comment by savey** [comment]
解决了么?

**Comment by lxge** [comment]
> 解决了么?

目前本地依然是这样子的, 其他人本地也是这样. 可能本地连接效率比用连接池效率高吧, 跟作者测试的结果好像不一致.

**Comment by savey** [comment]
我的是 MacBookPro，本地试了下，没有达到预期效果。不知道是否配置有错、我直接跑的 项目 test

**Comment by lxge** [comment]
> 我的是 MacBookPro，本地试了下，没有达到预期效果。不知道是否配置有错、我直接跑的 项目 test

是啊,前几天遇到一个也是mac跑,效率略低于原生连接方法,感觉本地提升不是很明显,有人说连接池是为了保证服务稳定,速度方面的话是不是连接分布式的那种数据库会有优势,不过暂时没试过.

**Comment by 84hero** [comment]
# SMProxy
`
<?php
/**
 * Created by PhpStorm.
 * User: louislivi
 * Date: 2018-12-09
 * Time: 10:10
 */
$servername = "127.0.0.1";
$username = "root";
$password = "root";
$dbname = "mysql";
$port   = 3366;
try {
    // 创建连接
    $conn = new mysqli($servername, $username, $password, $dbname, $port);
    // Check connection
    if ($conn->connect_error) {
        echo "Connect failed!" . $conn->connect_error . PHP_EOL;
    }
    echo 'Connect succeeded!' . PHP_EOL;

    $sql = "SELECT `Host`,`User`,`Plugin` FROM `mysql`.`user` limit 1";
    $result = $conn->query($sql);
    echo 'Executed query:' . $sql . PHP_EOL;
    if ($result->num_rows > 0) {
        echo 'Result: ' . json_encode($result->fetch_assoc()) . PHP_EOL;
    } else {
        echo "Result empty!" . PHP_EOL;
    }
    $conn->close();
} catch (\Exception $exception) {
    echo $exception ->getMessage();
}
?>
`
# 直连
`
<?php
/**
 * Created by PhpStorm.
 * User: louislivi
 * Date: 2018-12-09
 * Time: 10:10
 */
$servername = "127.0.0.1";
$username = "root";
$password = "root";
$dbname = "mysql";
$port   = 3306;
try {
    // 创建连接
    $conn = new mysqli($servername, $username, $password, $dbname, $port);
    // Check connection
    if ($conn->connect_error) {
        echo "Connect failed!" . $conn->connect_error . PHP_EOL;
    }
    echo 'Connect succeeded!' . PHP_EOL;

    $sql = "SELECT `Host`,`User`,`Plugin` FROM `mysql`.`user` limit 1";
    $result = $conn->query($sql);
    echo 'Executed query:' . $sql . PHP_EOL;
    if ($result->num_rows > 0) {
        echo 'Result: ' . json_encode($result->fetch_assoc()) . PHP_EOL;
    } else {
        echo "Result empty!" . PHP_EOL;
    }
    $conn->close();
} catch (\Exception $exception) {
    echo $exception ->getMessage();
}
?>

`

**Comment by lxge** [comment]
linux虚拟机我用你同样的代码, 结果还是会变慢. 我也不清楚是什么原因, CPU内存都还有很大空间,之前很多刚装的也这么说,会变慢(包括mac)
