### ISSUE TITLE
报：Fatal error: Uncaught Error: Call to undefined function SMProxy\go()

### ISSUE THREAD

**Issue by augustdai** [louislivi/SMProxy#59]
### Describe Your Environment (描述你的环境)

- System: 
- PHP version: 
- Mysql version: 
- Swoole version: 
- SMProxy version: 

### How to Reproduce the Problem? (如何重现问题)

1. 
2. 
3. 

### Expected Behavior (预期行为)

...

### Actual Behavior (实际行为)

...

### More Information (更多信息)

...

**Comment by louislivi** [comment]
@augustdai  在2.1.0或更高版本中如果开启了swoole.use_shortname，可以直接使用go关键词创建新的协程。 请检查你的配置！
