### ISSUE TITLE
建议作者进行以下检查

### ISSUE THREAD

**Issue by wi1dcard** [louislivi/smproxy#6]
1. Git commit message 中英混合是否不合适？且首行应为本次提交信息的标题。
2. README Markdown 语法是否太混乱？换行、标题、大小写、语法是否应该修改？
3. 是否应当编写对应单元测试并确保内存回收没有问题以保证运行稳定？
4. 是否应当使用守护进程，例如 Supervisor 等方式确保异常退出能够重启？
5. README 图片是否应当使用稳定的图床或直接保存在 repo 内，例如 `doc` 文件夹？
6. README 最后的配置项表格是否存在太多列、难以阅读的问题？
7. 若考虑向国外用户推广，是否应当准确翻译项目文档？

看好本项目的初衷和效果，但稳定性以及文档质量、代码质量，个人认为还有待提高。

**Comment by louislivi** [comment]
是存在这些问题，还存在很多问题 现在一个人开发有点搞不过来了 ，你有意向加入这个项目吗？可以共同将这个项目做好。

**Comment by wi1dcard** [comment]
@louislivi 我已经优化了 README，提交了 PR，可以直接合并。

See: #4

**Comment by louislivi** [comment]
@wi1dcard 已 merge
