### ISSUE TITLE
这个系统可以大规模商用吗

### ISSUE THREAD

**Issue by chuchengyi** [louislivi/SMProxy#61]
我们是一家sass化的电商平台，应用层的有很多应用是php开发的，想找一个可靠的数据库连接池。
想大规模商用，可以使用吗？
另外可以有什么合作方式，比如技术指导、技术咨询、付费可以聊。方便的化可以给个邮件，联系

**Comment by chuchengyi** [comment]
这个项目有没什么技术沙龙可以参加的

**Comment by louislivi** [comment]
QQ已回
