### ISSUE TITLE
动态切换数据库

### ISSUE THREAD

**Issue by stingbo** [louislivi/SMProxy#65]
### Describe Your Environment (描述你的环境)

- System: CentOS7
- PHP version: 7.2
- Mysql version: 5.6
- Swoole version: 4.4.2
- SMProxy version:  1.2.9

### How to Reproduce the Problem? (如何重现问题)
我们的应用是SAAS，多租户模式，每个租户的数据库是各自的，都是不一样的，新来一个租户会新增一个数据库，所以它的数据库是动态变化的，这个项目可以配置成数据库是动态切换的吗？

### Expected Behavior (预期行为)
我们的应用是SAAS，多租户模式，每个租户的数据库是各自的，都是不一样的，新来一个租户会新增一个数据库，所以它的数据库是动态变化的，这个项目可以配置成数据库是动态切换的吗？

### Actual Behavior (实际行为)

我们的应用是SAAS，多租户模式，每个租户的数据库是各自的，都是不一样的，新来一个租户会新增一个数据库，所以它的数据库是动态变化的，这个项目可以配置成数据库是动态切换的吗？

### More Information (更多信息)
我们的应用是SAAS，多租户模式，每个租户的数据库是各自的，都是不一样的，新来一个租户会新增一个数据库，所以它的数据库是动态变化的，这个项目可以配置成数据库是动态切换的吗？

**Comment by louislivi** [comment]
连接池无法动态切换数据库

**Comment by stingbo** [comment]
好的 谢谢，麻烦再问一句，laravel 有其它方案吗？

**Comment by louislivi** [comment]
什么其他方案？ 我知道的所有连接池都是无法动态切换数据库的。毕竟需要初始化你可以通过某种脚本自行实现动态添加

**Comment by stingbo** [comment]
也是，如果租户上万家，不同的库连接都有上万个了
