### ISSUE TITLE
有没有计划加入mongodb和redis连接池？

### ISSUE THREAD

**Issue by wo642436249** [louislivi/SMProxy#67]
### Describe Your Environment (描述你的环境)

- System: 
- PHP version: 
- Mysql version: 
- Swoole version: 
- SMProxy version: 

### How to Reproduce the Problem? (如何重现问题)

1. 
2. 
3. 

### Expected Behavior (预期行为)

...

### Actual Behavior (实际行为)

...

### More Information (更多信息)

...

**Comment by louislivi** [comment]
目前暂时没有
