### ISSUE TITLE
只能读取无法写入

### ISSUE THREAD

**Issue by menghuanzhixiang** [louislivi/SMProxy#69]
### Describe Your Environment (描述你的环境)

- System: centos7
- PHP version: 7.2
- Mysql version: 5.6
- Swoole version: 4.4.12
- SMProxy version: 最新

### How to Reproduce the Problem? (如何重现问题)

1. 网站程序wordpress,管理面板宝塔，web apache
2. 网站打开正常，但是一切写入操作全失败，比如无法评论，无法保存后台设置等等
3. 开启debug提示WordPress数据库错误： [3D000No database selected]

### Expected Behavior (预期行为)

...

### Actual Behavior (实际行为)

...

### More Information (更多信息)

...

**Comment by louislivi** [comment]
因为wordpress 默认未指定数据库连接
这里需要改成你的数据库名称就可以了 /wp-includes/wp-db.php

![image](https://user-images.githubusercontent.com/23403807/72491883-628d6d00-3856-11ea-8aee-66c52777e6b0.png)

最新文档已更新wordpress配置
https://smproxy.louislivi.com/#/README?id=%e5%9c%a8%e9%a1%b9%e7%9b%ae%e4%b8%ad%e5%a6%82%e4%bd%95%e8%bf%9b%e8%a1%8c%e9%85%8d%e7%bd%ae
