### ISSUE TITLE
docker 启动配置问题

### ISSUE THREAD

**Issue by bykiss** [louislivi/SMProxy#70]
### Describe Your Environment (描述你的环境)

- System: 
- PHP version: 7.2
- Mysql version: 5.7
- Swoole version: 4.4.15
- SMProxy version: 1.3.1
 Docker version 18.06.1-ce,
### How to Reproduce the Problem? (如何重现问题)

1. 利用源码中的Dockerfile 安装
2. maxConns或者maxSpareConns 设置为数字，比如"maxConns": 10 或者"maxConns": “10”
3. maxConns或者maxSpareConns 设置为 swoole_cpu_num()/2 

### Expected Behavior (预期行为)
能正常启动

### Actual Behavior (实际行为)
启动失败，日志显示
[warning] Invalid maxSpareConns or maxConns in writeSΜvulscan (phar:///usr/local/smproxy/SMProxy/src/MysqlPool/MySQLPool.php:63)

### More Information (更多信息)
CPU为16核
当改回  swoole_cpu_num() 时，且只能为swoole_cpu_num()  ，启动成功
...

**Comment by louislivi** [comment]
`maxConns`或者`maxSpareConns`必须要大于`worker_num`因为`worker_num`默认为`swoole_cpu_num()`，你的cpu为16核，所以`maxConns`和`maxSpareConns`必须要大于16，所以设置为10 或`swoole_cpu_num()/2`会出现该错误`[warning] Invalid maxSpareConns or maxConns in XXX`该错误。

**Comment by bykiss** [comment]
thx
