### ISSUE TITLE
运行SMProxy显示segment fault

### ISSUE THREAD

**Issue by shyandsy** [louislivi/SMProxy#74]
### Describe Your Environment (描述你的环境)

- System:  centos 7.6
- PHP version:  7.3
- Mysql version:  8
- Swoole version:  4.5
- SMProxy version: 1.3.1

### How to Reproduce the Problem? (如何重现问题)

1. wget https://github.com/louislivi/SMProxy/releases/download/v1.3.1/smproxy.tar.gz
2. tar xvzf smproxy.tar.gz
3. cd smproxy
4. 修改conf/server.json, conf/database.json
5. chmox + x SMProxy
6. ./SMProxy start

segment fault
![image](https://user-images.githubusercontent.com/5271457/80690768-de5bae80-8b01-11ea-94b7-7ca51bd91450.png)
...

**Comment by louislivi** [comment]
查看日志文件，找到详细的错误日志。
