### ISSUE TITLE
运行直接报错

### ISSUE THREAD

**Issue by hesunfly** [louislivi/SMProxy#75]
PHP Fatal error:  Uncaught Error: Call to undefined function SMProxy\go() in /Users/hesunfly/Workspace/code/php/smproxy/src/Base.php:30

只用pear和git下载的运行之后log里面全部是这个错，循环报错。
系统：macbook pro
php：7.2
swoole: 4.5.1

**Comment by louislivi** [comment]
修改 php.ini 设置 swoole.use_shortname=On/Off 来开启 / 关闭短名，默认为开启。
