### ISSUE TITLE
swoole.log 时常出现连接被关闭的情况

### ISSUE THREAD

**Issue by qinlodestar** [louislivi/SMProxy#78]
### Describe Your Environment (描述你的环境)

- System: centos7
- PHP version: 7.3.0
- Mysql version:  5.6
- Swoole version: 4.5.2
- SMProxy version: 1.3.0

### Actual Behavior (实际行为)
swoole.log 有以下报警
[2020-07-09 23:05:47 *23016.1]	NOTICE	swFactoryProcess_finish (ERRNO 1004): send 16060 byte failed, because connection[fd=8531] is closed

...

### More Information (更多信息)

...

**Comment by louislivi** [comment]
这种情况是swoole检测到客户端已经断开连接，无法发送数据的警告。可以忽略。

**Comment by qinlodestar** [comment]
有正常的请求已经报错了

**Comment by louislivi** [comment]
可以尝试更新swoole 版本进行解决。
