### ISSUE TITLE
php7.3 下 cpu一直很高

### ISSUE THREAD

**Issue by quqiufeng** [louislivi/SMProxy#80]
### Describe Your Environment (描述你的环境)

- System: 
- PHP version: 7.3.19
- Mysql version: 5.6
- Swoole version: 4.5.2
- SMProxy version: v1.3.1

cpu 一直100%

连接数配置为
swoole_cpu_num()*40

两个cpu 一直100%

**Comment by quqiufeng** [comment]
"serverInfo": {
      "": {
        "write": {
          "host": [""],
          "port": 3306,
          "timeout": 5,
          "account": ""
        },
        "read": {
          "host": [""],
          "port": 3306,
          "timeout": 5,
          "account": "",
          "startConns": "swoole_cpu_num()*40",
          "maxSpareConns": "swoole_cpu_num()*40",
          "maxSpareExp": 3600,
          "maxConns": "swoole_cpu_num()*40"
        }
      }
    },
    "databases": {
      "beautinow": {
        "serverInfo": "",
        "startConns": "swoole_cpu_num()*40",
        "maxSpareConns": "swoole_cpu_num()*40",
        "maxSpareExp": 3600,
        "maxConns": "swoole_cpu_num()*40",
        "charset": "utf8mb4"
      }
    }
  }

**Comment by quqiufeng** [comment]
升级到  swoole 4.5.3 后  启动报错
WARNING	swTableColumn_add: unkown column type

**Comment by louislivi** [comment]
连接数不建议设置过大

**Comment by quqiufeng** [comment]
> 连接数不建议设置过大
升级到 swoole 4.5.3 后 启动报错
WARNING swTableColumn_add: unkown column type

**Comment by chunpat** [comment]
> 连接数不建议设置过大

一个连接占用多少资源？cpu飙高是什么原因？
