### ISSUE TITLE
PDO连接数据库是否也能提高性能

### ISSUE THREAD

**Issue by v-sir** [louislivi/SMProxy#83]
### Describe Your Environment (描述你的环境)

- System: 
- PHP version: v7.2.34
- Mysql version: v 5.6.0
- Swoole version:  v4.5.6
- SMProxy version: v1.3.1

### How to Reproduce the Problem? (如何重现问题)

1. 连接数据库是不是只能采用mysqli连接，使用PDO是否也一致。采用PDO连接ab压力测试甚至比原链接还慢。已经调整最大连接数
2. 
3. 

### Expected Behavior (预期行为)
启用连接池较未启用连接池有明显的性能提升
...

### Actual Behavior (实际行为)
请求时间还较原始情况慢
...

### More Information (更多信息)

...

**Comment by nilfei** [comment]
你设置了pdo驱动为长链接了吗

**Comment by louislivi** [comment]
代理连接池，多了一层代理在非分布式情况下，有性能差异是很正常的。
