### ISSUE TITLE
Swoole\Server\Port::set(): option [package_length_func] does not support with ZTS

### ISSUE THREAD

**Issue by LeslieLeung** [louislivi/SMProxy#85]
### Describe Your Environment (描述你的环境)

- System: CentOS 7.8
- PHP version: 7.2.22
- Mysql version: 5.7.29
- Swoole version: 4.5.9
- SMProxy version: 1.3.1

### How to Reproduce the Problem? (如何重现问题)

While starting SMProxy, the following error occured:

```
Server starting ...
PHP Fatal error:  Swoole\Server\Port::set(): option [package_length_func] does not support with ZTS in phar:///root/smproxy/SMProxy/src/BaseServer.php on line 62
```

**Comment by louislivi** [comment]
建议用nts版本
